//This file was automatically generated by Portoa.Tests.DataGenerator.Generate_country_enum() on 3/11/2011 3:15:05 PM
//Don't modify this file directory, instead edit the code that generated this file

using System.ComponentModel;
using Portoa.Util;

namespace Portoa.Globalization {
	// ReSharper disable InconsistentNaming
	///<summary>Auto-generated enumeration of every country supported by <see cref="System.Globalization.CultureInfo"/></summary>
	public enum Country {
		///<summary>The country Afghanistan</summary>
		[Description("Afghanistan")]
		Afghanistan = 3,
		///<summary>The country Albania</summary>
		[Description("Albania")]
		Albania = 6,
		///<summary>The country Algeria</summary>
		[Description("Algeria")]
		Algeria = 4,
		///<summary>The country Argentina</summary>
		[Description("Argentina")]
		Argentina = 11,
		///<summary>The country Armenia</summary>
		[Description("Armenia")]
		Armenia = 7,
		///<summary>The country Australia</summary>
		[Description("Australia")]
		Australia = 12,
		///<summary>The country Austria</summary>
		[Description("Austria")]
		Austria = 14,
		///<summary>The country Azerbaijan</summary>
		[Description("Azerbaijan")]
		Azerbaijan = 5,
		///<summary>The country Bahrain</summary>
		[Description("Bahrain")]
		Bahrain = 17,
		///<summary>The country Bangladesh</summary>
		[Description("Bangladesh")]
		Bangladesh = 23,
		///<summary>The country Belarus</summary>
		[Description("Belarus")]
		Belarus = 29,
		///<summary>The country Belgium</summary>
		[Description("Belgium")]
		Belgium = 21,
		///<summary>The country Belize</summary>
		[Description("Belize")]
		Belize = 24,
		///<summary>The country Bolivarian Republic of Venezuela</summary>
		[Description("Bolivarian Republic of Venezuela")]
		BolivarianRepublicOfVenezuela = 249,
		///<summary>The country Bolivia</summary>
		[Description("Bolivia")]
		Bolivia = 26,
		///<summary>The country Bosnia and Herzegovina</summary>
		[Description("Bosnia and Herzegovina")]
		BosniaAndHerzegovina = 25,
		///<summary>The country Brazil</summary>
		[Description("Brazil")]
		Brazil = 32,
		///<summary>The country Brunei Darussalam</summary>
		[Description("Brunei Darussalam")]
		BruneiDarussalam = 37,
		///<summary>The country Bulgaria</summary>
		[Description("Bulgaria")]
		Bulgaria = 35,
		///<summary>The country Cambodia</summary>
		[Description("Cambodia")]
		Cambodia = 40,
		///<summary>The country Canada</summary>
		[Description("Canada")]
		Canada = 39,
		///<summary>The country Caribbean</summary>
		[Description("Caribbean")]
		Caribbean = 124,
		///<summary>The country Chile</summary>
		[Description("Chile")]
		Chile = 46,
		///<summary>The country Colombia</summary>
		[Description("Colombia")]
		Colombia = 51,
		///<summary>The country Costa Rica</summary>
		[Description("Costa Rica")]
		CostaRica = 54,
		///<summary>The country Croatia</summary>
		[Description("Croatia")]
		Croatia = 108,
		///<summary>The country Czech Republic</summary>
		[Description("Czech Republic")]
		CzechRepublic = 75,
		///<summary>The country Denmark</summary>
		[Description("Denmark")]
		Denmark = 61,
		///<summary>The country Dominican Republic</summary>
		[Description("Dominican Republic")]
		DominicanRepublic = 65,
		///<summary>The country Ecuador</summary>
		[Description("Ecuador")]
		Ecuador = 66,
		///<summary>The country Egypt</summary>
		[Description("Egypt")]
		Egypt = 67,
		///<summary>The country El Salvador</summary>
		[Description("El Salvador")]
		ElSalvador = 72,
		///<summary>The country Estonia</summary>
		[Description("Estonia")]
		Estonia = 70,
		///<summary>The country Ethiopia</summary>
		[Description("Ethiopia")]
		Ethiopia = 73,
		///<summary>The country Faroe Islands</summary>
		[Description("Faroe Islands")]
		FaroeIslands = 81,
		///<summary>The country Finland</summary>
		[Description("Finland")]
		Finland = 77,
		///<summary>The country France</summary>
		[Description("France")]
		France = 84,
		///<summary>The country Georgia</summary>
		[Description("Georgia")]
		Georgia = 88,
		///<summary>The country Germany</summary>
		[Description("Germany")]
		Germany = 94,
		///<summary>The country Greece</summary>
		[Description("Greece")]
		Greece = 98,
		///<summary>The country Greenland</summary>
		[Description("Greenland")]
		Greenland = 93,
		///<summary>The country Guatemala</summary>
		[Description("Guatemala")]
		Guatemala = 99,
		///<summary>The country Honduras</summary>
		[Description("Honduras")]
		Honduras = 106,
		///<summary>The country Hong Kong S.A.R.</summary>
		[Description("Hong Kong S.A.R.")]
		HongKongSAR = 104,
		///<summary>The country Hungary</summary>
		[Description("Hungary")]
		Hungary = 109,
		///<summary>The country Iceland</summary>
		[Description("Iceland")]
		Iceland = 110,
		///<summary>The country India</summary>
		[Description("India")]
		India = 113,
		///<summary>The country Indonesia</summary>
		[Description("Indonesia")]
		Indonesia = 111,
		///<summary>The country Iran</summary>
		[Description("Iran")]
		Iran = 116,
		///<summary>The country Iraq</summary>
		[Description("Iraq")]
		Iraq = 121,
		///<summary>The country Ireland</summary>
		[Description("Ireland")]
		Ireland = 68,
		///<summary>The country Islamic Republic of Pakistan</summary>
		[Description("Islamic Republic of Pakistan")]
		IslamicRepublicOfPakistan = 190,
		///<summary>The country Israel</summary>
		[Description("Israel")]
		Israel = 117,
		///<summary>The country Italy</summary>
		[Description("Italy")]
		Italy = 118,
		///<summary>The country Jamaica</summary>
		[Description("Jamaica")]
		Jamaica = 124,
		///<summary>The country Japan</summary>
		[Description("Japan")]
		Japan = 122,
		///<summary>The country Jordan</summary>
		[Description("Jordan")]
		Jordan = 126,
		///<summary>The country Kazakhstan</summary>
		[Description("Kazakhstan")]
		Kazakhstan = 137,
		///<summary>The country Kenya</summary>
		[Description("Kenya")]
		Kenya = 129,
		///<summary>The country Korea</summary>
		[Description("Korea")]
		Korea = 134,
		///<summary>The country Kuwait</summary>
		[Description("Kuwait")]
		Kuwait = 136,
		///<summary>The country Kyrgyzstan</summary>
		[Description("Kyrgyzstan")]
		Kyrgyzstan = 130,
		///<summary>The country Lao P.D.R.</summary>
		[Description("Lao P.D.R.")]
		LaoPDR = 138,
		///<summary>The country Latvia</summary>
		[Description("Latvia")]
		Latvia = 140,
		///<summary>The country Lebanon</summary>
		[Description("Lebanon")]
		Lebanon = 139,
		///<summary>The country Libya</summary>
		[Description("Libya")]
		Libya = 148,
		///<summary>The country Liechtenstein</summary>
		[Description("Liechtenstein")]
		Liechtenstein = 145,
		///<summary>The country Lithuania</summary>
		[Description("Lithuania")]
		Lithuania = 141,
		///<summary>The country Luxembourg</summary>
		[Description("Luxembourg")]
		Luxembourg = 147,
		///<summary>The country Macao S.A.R.</summary>
		[Description("Macao S.A.R.")]
		MacaoSAR = 151,
		///<summary>The country Macedonia (FYROM)</summary>
		[Description("Macedonia (FYROM)")]
		MacedoniaFYROM = 19618,
		///<summary>The country Malaysia</summary>
		[Description("Malaysia")]
		Malaysia = 167,
		///<summary>The country Maldives</summary>
		[Description("Maldives")]
		Maldives = 165,
		///<summary>The country Malta</summary>
		[Description("Malta")]
		Malta = 163,
		///<summary>The country Mexico</summary>
		[Description("Mexico")]
		Mexico = 166,
		///<summary>The country Mongolia</summary>
		[Description("Mongolia")]
		Mongolia = 154,
		///<summary>The country Montenegro</summary>
		[Description("Montenegro")]
		Montenegro = 270,
		///<summary>The country Morocco</summary>
		[Description("Morocco")]
		Morocco = 159,
		///<summary>The country Nepal</summary>
		[Description("Nepal")]
		Nepal = 178,
		///<summary>The country Netherlands</summary>
		[Description("Netherlands")]
		Netherlands = 176,
		///<summary>The country New Zealand</summary>
		[Description("New Zealand")]
		NewZealand = 183,
		///<summary>The country Nicaragua</summary>
		[Description("Nicaragua")]
		Nicaragua = 182,
		///<summary>The country Nigeria</summary>
		[Description("Nigeria")]
		Nigeria = 175,
		///<summary>The country Norway</summary>
		[Description("Norway")]
		Norway = 177,
		///<summary>The country Oman</summary>
		[Description("Oman")]
		Oman = 164,
		///<summary>The country Panama</summary>
		[Description("Panama")]
		Panama = 192,
		///<summary>The country Paraguay</summary>
		[Description("Paraguay")]
		Paraguay = 185,
		///<summary>The country People's Republic of China</summary>
		[Description("People's Republic of China")]
		PeoplesRepublicOfChina = 45,
		///<summary>The country Peru</summary>
		[Description("Peru")]
		Peru = 187,
		///<summary>The country Philippines</summary>
		[Description("Philippines")]
		Philippines = 201,
		///<summary>The country Poland</summary>
		[Description("Poland")]
		Poland = 191,
		///<summary>The country Portugal</summary>
		[Description("Portugal")]
		Portugal = 193,
		///<summary>The country Principality of Monaco</summary>
		[Description("Principality of Monaco")]
		PrincipalityOfMonaco = 158,
		///<summary>The country Puerto Rico</summary>
		[Description("Puerto Rico")]
		PuertoRico = 202,
		///<summary>The country Qatar</summary>
		[Description("Qatar")]
		Qatar = 197,
		///<summary>The country Romania</summary>
		[Description("Romania")]
		Romania = 200,
		///<summary>The country Russia</summary>
		[Description("Russia")]
		Russia = 203,
		///<summary>The country Rwanda</summary>
		[Description("Rwanda")]
		Rwanda = 204,
		///<summary>The country Saudi Arabia</summary>
		[Description("Saudi Arabia")]
		SaudiArabia = 205,
		///<summary>The country Senegal</summary>
		[Description("Senegal")]
		Senegal = 210,
		///<summary>The country Serbia</summary>
		[Description("Serbia")]
		Serbia = 271,
		///<summary>The country Serbia and Montenegro (Former)</summary>
		[Description("Serbia and Montenegro (Former)")]
		SerbiaAndMontenegroFormer = 269,
		///<summary>The country Singapore</summary>
		[Description("Singapore")]
		Singapore = 215,
		///<summary>The country Slovakia</summary>
		[Description("Slovakia")]
		Slovakia = 143,
		///<summary>The country Slovenia</summary>
		[Description("Slovenia")]
		Slovenia = 212,
		///<summary>The country South Africa</summary>
		[Description("South Africa")]
		SouthAfrica = 209,
		///<summary>The country Spain</summary>
		[Description("Spain")]
		Spain = 217,
		///<summary>The country Sri Lanka</summary>
		[Description("Sri Lanka")]
		SriLanka = 42,
		///<summary>The country Sweden</summary>
		[Description("Sweden")]
		Sweden = 221,
		///<summary>The country Switzerland</summary>
		[Description("Switzerland")]
		Switzerland = 223,
		///<summary>The country Syria</summary>
		[Description("Syria")]
		Syria = 222,
		///<summary>The country Taiwan</summary>
		[Description("Taiwan")]
		Taiwan = 237,
		///<summary>The country Tajikistan</summary>
		[Description("Tajikistan")]
		Tajikistan = 228,
		///<summary>The country Thailand</summary>
		[Description("Thailand")]
		Thailand = 227,
		///<summary>The country Trinidad and Tobago</summary>
		[Description("Trinidad and Tobago")]
		TrinidadAndTobago = 225,
		///<summary>The country Tunisia</summary>
		[Description("Tunisia")]
		Tunisia = 234,
		///<summary>The country Turkey</summary>
		[Description("Turkey")]
		Turkey = 235,
		///<summary>The country Turkmenistan</summary>
		[Description("Turkmenistan")]
		Turkmenistan = 238,
		///<summary>The country U.A.E.</summary>
		[Description("U.A.E.")]
		UAE = 224,
		///<summary>The country Ukraine</summary>
		[Description("Ukraine")]
		Ukraine = 241,
		///<summary>The country United Kingdom</summary>
		[Description("United Kingdom")]
		UnitedKingdom = 242,
		///<summary>The country United States</summary>
		[Description("United States")]
		UnitedStates = 244,
		///<summary>The country Uruguay</summary>
		[Description("Uruguay")]
		Uruguay = 246,
		///<summary>The country Uzbekistan</summary>
		[Description("Uzbekistan")]
		Uzbekistan = 247,
		///<summary>The country Vietnam</summary>
		[Description("Vietnam")]
		Vietnam = 251,
		///<summary>The country Yemen</summary>
		[Description("Yemen")]
		Yemen = 261,
		///<summary>The country Zimbabwe</summary>
		[Description("Zimbabwe")]
		Zimbabwe = 264,

	}
	// ReSharper restore InconsistentNaming

	public static class CountryExtensions {
		/// <summary> Gets the human-readable display name for a <see cref="Country"/> </summary>
		public static string GetDisplayName(this Country country) {
			return country.GetAttributes<DescriptionAttribute>()[0].Description;
		}
	}
}